/*
 * This module will display the results of played matches for the FIFA world cup 2014
 * It will be controlled by a varible called select which the user sets using the jComboBox.
 * This will toggle the visability of 8 jPanels (one for each group) so the respective panel is visable
 * @johnoshea x13104977
 * 
 * PROGRESS LOG:
 * 
 * Commit 1: Basic layout was established. The main Panels dimensions were agreed upon by the group. 
 *           I'm going to controll the module with a single jComboBox.
 *           The content will be displayed in seperate jPanels. I haven't decided how I'll display info inside the panels yet (ie. labels, text areas etc...).
 * 
 * Commit 2: Didn't actually get any coding done, I just planned out my next commit on paper and read into using the jComboBox.
 *           Fixed a problem in regards to importing the swing layout library.
 * 
 * Commit 3: Added a button and coded the event handeler. (See line 114). On click, this button takes the selected value from the jComboBox.
 *           This value is then stored in the variable String select. The event handler also exicutes a switch statement (written using else if for now) (see line 135).
 *           This statement will toggle the respective panel to visable and the other 7 to invisable.
 * 
 * Commit 4: TODO: 1. Design the panels to display the results. 
 *                 2. Create a class to toggle all those panels to visable=false; (Might just borrow the one from MainController.
 *                 3. Finish coding the switch statement to controll the visability of the panels.
 *                 4. Set the background image (agree on this with group).
 *                 5. Set the fonts (agree on this with group).
 * 
 * Commit 5: TODO: 1. Bug testing and troubleshooting.
 *                 2. Any last font or design changes (agree w/ group).
 *                 3. Bug test entire project (do this as a group).
 */
package nci.OOPGroup03;

import javax.swing.JOptionPane;

/**
 *
 * @author johnoshea
 */
public class ResultsModule extends javax.swing.JPanel {

    //Creates new form ResultsModule
     
    public ResultsModule() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 0));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 32)); // NOI18N
        jLabel1.setText("Results");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel2.setText("Chose Group");

        jComboBox1.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "D", "E", "F", "G" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextField1.setText("jTextField1");

        jButton1.setText("Go!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(249, 249, 249)
                        .add(jLabel1))
                    .add(layout.createSequentialGroup()
                        .add(201, 201, 201)
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton1))
                    .add(layout.createSequentialGroup()
                        .add(132, 132, 132)
                        .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 408, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(27, 27, 27)
                .add(jLabel1)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton1))
                .add(84, 84, 84)
                .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // I don't want this action to do anything, the event will be called when the user clicks the button (line103).
        // This just assigns the variable 'String select' which will controll the if, if else, else statements (line 108) 
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Line 129 (commeneted out) is just for testing (breakpoint 1)
        // jTextField1.setText("Results for Group " + jComboBox1.getSelectedItem().toString());
       String select = (String) jComboBox1.getSelectedItem();
       //NOTE! This will be changed to a 'switch' statement once I am happy everything else in the module is working as intended
       // This selection will toggle the visability of the respective JTextArea to visable = true and toggle the other 5 text areas to visable = false    

       if (select == "A") {System.out.println("Test A successful");}
       else if (select == "B") {System.out.println("Test B successful");}
       else if (select == "C") {System.out.println("Test C successful");}
       else if (select == "D") {System.out.println("Test D successful");}
       else if (select == "E") {System.out.println("Test E successful");}
       else if (select == "F") {System.out.println("Test F successful");}
       else if (select == "G") {System.out.println("Test G successful");}
       else {System.out.println("Oops! Something went wrong in ResultsModule (breakpoint 2)");}
    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
